
services:
  php:
    build:
      target: frankenphp_dev
    ports:
      - target: 80
        published: ${HTTP_PORT:-8080}
      - target: 443
        published: ${HTTPS_PORT:-8443}

###> doctrine/doctrine-bundle ###
  database:
    ports:
      - "5432"
###< doctrine/doctrine-bundle ###

###> symfony/mailer ###
  mailer:
    image: axllent/mailpit
    ports:
      - "1025"
      - "8025:8025"
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
###< symfony/mailer ###
