<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260619144358 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE bonus_photo (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, challenge VARCHAR(255) NOT NULL, photo VARCHAR(255) DEFAULT NULL, comment TEXT DEFAULT NULL, consent_to_publish BOOLEAN NOT NULL, status VARCHAR(255) NOT NULL, points_awarded DOUBLE PRECISION DEFAULT NULL, submitted_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, reviewed_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, user_id INT NOT NULL, city_edition_id INT NOT NULL, reviewed_by_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_C10F07BBA76ED395 ON bonus_photo (user_id)');
        $this->addSql('CREATE INDEX IDX_C10F07BB1951AAA9 ON bonus_photo (city_edition_id)');
        $this->addSql('CREATE INDEX IDX_C10F07BBFC6B21F1 ON bonus_photo (reviewed_by_id)');
        $this->addSql('CREATE TABLE bonus_photo_config (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, challenge VARCHAR(255) NOT NULL, points DOUBLE PRECISION NOT NULL, city_edition_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_5E6FFDAF1951AAA9 ON bonus_photo_config (city_edition_id)');
        $this->addSql('CREATE TABLE city (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(100) NOT NULL, slug VARCHAR(100) NOT NULL, organization_name VARCHAR(200) DEFAULT NULL, organization_description TEXT DEFAULT NULL, organization_logo VARCHAR(255) DEFAULT NULL, contact_email VARCHAR(180) DEFAULT NULL, social_link1_type VARCHAR(255) DEFAULT NULL, social_link1_url VARCHAR(255) DEFAULT NULL, social_link2_type VARCHAR(255) DEFAULT NULL, social_link2_url VARCHAR(255) DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_2D5B0234989D9B62 ON city (slug)');
        $this->addSql('CREATE TABLE city_edition (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, target_participants INT NOT NULL, target_distance_km INT NOT NULL, points_per_day DOUBLE PRECISION NOT NULL, points_per_km_bike DOUBLE PRECISION NOT NULL, points_per_km_walk DOUBLE PRECISION NOT NULL, suspicious_distance_bike DOUBLE PRECISION NOT NULL, suspicious_distance_walk DOUBLE PRECISION NOT NULL, registrations_open BOOLEAN NOT NULL, trips_entry_open BOOLEAN NOT NULL, photo_challenges_enabled BOOLEAN NOT NULL, rankings_public BOOLEAN NOT NULL, profiles_public BOOLEAN NOT NULL, organizer_message TEXT DEFAULT NULL, city_id INT NOT NULL, edition_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_15D9A64D8BAC62AF ON city_edition (city_id)');
        $this->addSql('CREATE INDEX IDX_15D9A64D74281A5E ON city_edition (edition_id)');
        $this->addSql('CREATE TABLE city_edition_participants (city_edition_id INT NOT NULL, user_id INT NOT NULL, PRIMARY KEY (city_edition_id, user_id))');
        $this->addSql('CREATE INDEX IDX_F3CD6E841951AAA9 ON city_edition_participants (city_edition_id)');
        $this->addSql('CREATE INDEX IDX_F3CD6E84A76ED395 ON city_edition_participants (user_id)');
        $this->addSql('CREATE TABLE counter_step (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(150) NOT NULL, distance_km INT NOT NULL, position INT NOT NULL, city_edition_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_C34275B1951AAA9 ON counter_step (city_edition_id)');
        $this->addSql('CREATE TABLE edition (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(150) NOT NULL, year INT NOT NULL, start_date DATE NOT NULL, end_date DATE NOT NULL, warmup_start_date DATE DEFAULT NULL, warmup_end_date DATE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE partner (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(150) NOT NULL, website_url VARCHAR(255) DEFAULT NULL, description TEXT DEFAULT NULL, logo VARCHAR(255) DEFAULT NULL, position INT NOT NULL, city_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_312B3E168BAC62AF ON partner (city_id)');
        $this->addSql('CREATE TABLE reset_password_request (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, selector VARCHAR(20) NOT NULL, hashed_token VARCHAR(100) NOT NULL, requested_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, expires_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_7CE748AA76ED395 ON reset_password_request (user_id)');
        $this->addSql('CREATE TABLE team (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(150) NOT NULL, slug VARCHAR(150) NOT NULL, description TEXT DEFAULT NULL, is_public BOOLEAN NOT NULL, avatar VARCHAR(255) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, city_id INT NOT NULL, created_by_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_C4E0A61F8BAC62AF ON team (city_id)');
        $this->addSql('CREATE INDEX IDX_C4E0A61FB03A8386 ON team (created_by_id)');
        $this->addSql('CREATE TABLE team_members (team_id INT NOT NULL, user_id INT NOT NULL, PRIMARY KEY (team_id, user_id))');
        $this->addSql('CREATE INDEX IDX_BAD9A3C8296CD8AE ON team_members (team_id)');
        $this->addSql('CREATE INDEX IDX_BAD9A3C8A76ED395 ON team_members (user_id)');
        $this->addSql('CREATE TABLE trip (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, mode VARCHAR(255) NOT NULL, distance_km DOUBLE PRECISION NOT NULL, trip_date DATE NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, points_generated DOUBLE PRECISION NOT NULL, user_id INT NOT NULL, city_edition_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_7656F53BA76ED395 ON trip (user_id)');
        $this->addSql('CREATE INDEX IDX_7656F53B1951AAA9 ON trip (city_edition_id)');
        $this->addSql('CREATE TABLE "user" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(180) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, first_name VARCHAR(100) NOT NULL, last_name VARCHAR(100) NOT NULL, username VARCHAR(100) NOT NULL, cyclist_profile VARCHAR(255) DEFAULT NULL, bike_type VARCHAR(255) DEFAULT NULL, perceived_benefit VARCHAR(255) DEFAULT NULL, main_barrier VARCHAR(255) DEFAULT NULL, gender VARCHAR(255) DEFAULT NULL, age INT DEFAULT NULL, receive_emails BOOLEAN NOT NULL, public_profile BOOLEAN NOT NULL, avatar VARCHAR(255) DEFAULT NULL, personal_token VARCHAR(36) NOT NULL, city_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_8D93D649E7927C74 ON "user" (email)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_8D93D649F85E0677 ON "user" (username)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_8D93D64976EE72D ON "user" (personal_token)');
        $this->addSql('CREATE INDEX IDX_8D93D6498BAC62AF ON "user" (city_id)');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750 ON messenger_messages (queue_name, available_at, delivered_at, id)');
        $this->addSql('ALTER TABLE bonus_photo ADD CONSTRAINT FK_C10F07BBA76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE bonus_photo ADD CONSTRAINT FK_C10F07BB1951AAA9 FOREIGN KEY (city_edition_id) REFERENCES city_edition (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE bonus_photo ADD CONSTRAINT FK_C10F07BBFC6B21F1 FOREIGN KEY (reviewed_by_id) REFERENCES "user" (id)');
        $this->addSql('ALTER TABLE bonus_photo_config ADD CONSTRAINT FK_5E6FFDAF1951AAA9 FOREIGN KEY (city_edition_id) REFERENCES city_edition (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE city_edition ADD CONSTRAINT FK_15D9A64D8BAC62AF FOREIGN KEY (city_id) REFERENCES city (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE city_edition ADD CONSTRAINT FK_15D9A64D74281A5E FOREIGN KEY (edition_id) REFERENCES edition (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE city_edition_participants ADD CONSTRAINT FK_F3CD6E841951AAA9 FOREIGN KEY (city_edition_id) REFERENCES city_edition (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE city_edition_participants ADD CONSTRAINT FK_F3CD6E84A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE counter_step ADD CONSTRAINT FK_C34275B1951AAA9 FOREIGN KEY (city_edition_id) REFERENCES city_edition (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE partner ADD CONSTRAINT FK_312B3E168BAC62AF FOREIGN KEY (city_id) REFERENCES city (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE reset_password_request ADD CONSTRAINT FK_7CE748AA76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE team ADD CONSTRAINT FK_C4E0A61F8BAC62AF FOREIGN KEY (city_id) REFERENCES city (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE team ADD CONSTRAINT FK_C4E0A61FB03A8386 FOREIGN KEY (created_by_id) REFERENCES "user" (id)');
        $this->addSql('ALTER TABLE team_members ADD CONSTRAINT FK_BAD9A3C8296CD8AE FOREIGN KEY (team_id) REFERENCES team (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE team_members ADD CONSTRAINT FK_BAD9A3C8A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE trip ADD CONSTRAINT FK_7656F53BA76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE trip ADD CONSTRAINT FK_7656F53B1951AAA9 FOREIGN KEY (city_edition_id) REFERENCES city_edition (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE "user" ADD CONSTRAINT FK_8D93D6498BAC62AF FOREIGN KEY (city_id) REFERENCES city (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE bonus_photo DROP CONSTRAINT FK_C10F07BBA76ED395');
        $this->addSql('ALTER TABLE bonus_photo DROP CONSTRAINT FK_C10F07BB1951AAA9');
        $this->addSql('ALTER TABLE bonus_photo DROP CONSTRAINT FK_C10F07BBFC6B21F1');
        $this->addSql('ALTER TABLE bonus_photo_config DROP CONSTRAINT FK_5E6FFDAF1951AAA9');
        $this->addSql('ALTER TABLE city_edition DROP CONSTRAINT FK_15D9A64D8BAC62AF');
        $this->addSql('ALTER TABLE city_edition DROP CONSTRAINT FK_15D9A64D74281A5E');
        $this->addSql('ALTER TABLE city_edition_participants DROP CONSTRAINT FK_F3CD6E841951AAA9');
        $this->addSql('ALTER TABLE city_edition_participants DROP CONSTRAINT FK_F3CD6E84A76ED395');
        $this->addSql('ALTER TABLE counter_step DROP CONSTRAINT FK_C34275B1951AAA9');
        $this->addSql('ALTER TABLE partner DROP CONSTRAINT FK_312B3E168BAC62AF');
        $this->addSql('ALTER TABLE reset_password_request DROP CONSTRAINT FK_7CE748AA76ED395');
        $this->addSql('ALTER TABLE team DROP CONSTRAINT FK_C4E0A61F8BAC62AF');
        $this->addSql('ALTER TABLE team DROP CONSTRAINT FK_C4E0A61FB03A8386');
        $this->addSql('ALTER TABLE team_members DROP CONSTRAINT FK_BAD9A3C8296CD8AE');
        $this->addSql('ALTER TABLE team_members DROP CONSTRAINT FK_BAD9A3C8A76ED395');
        $this->addSql('ALTER TABLE trip DROP CONSTRAINT FK_7656F53BA76ED395');
        $this->addSql('ALTER TABLE trip DROP CONSTRAINT FK_7656F53B1951AAA9');
        $this->addSql('ALTER TABLE "user" DROP CONSTRAINT FK_8D93D6498BAC62AF');
        $this->addSql('DROP TABLE bonus_photo');
        $this->addSql('DROP TABLE bonus_photo_config');
        $this->addSql('DROP TABLE city');
        $this->addSql('DROP TABLE city_edition');
        $this->addSql('DROP TABLE city_edition_participants');
        $this->addSql('DROP TABLE counter_step');
        $this->addSql('DROP TABLE edition');
        $this->addSql('DROP TABLE partner');
        $this->addSql('DROP TABLE reset_password_request');
        $this->addSql('DROP TABLE team');
        $this->addSql('DROP TABLE team_members');
        $this->addSql('DROP TABLE trip');
        $this->addSql('DROP TABLE "user"');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
